/** Class names of the menu; every selector in the stylesheet is scoped to a `dcm-` class. */
export const CLASS = {
  root: 'dcm-root',
  scrim: 'dcm-scrim',
  panel: 'dcm-panel',
  header: 'dcm-header',
  crumb: 'dcm-crumb',
  back: 'dcm-back',
  field: 'dcm-field',
  fieldIcon: 'dcm-field-icon',
  input: 'dcm-input',
  close: 'dcm-close',
  scope: 'dcm-scope',
  list: 'dcm-list',
  group: 'dcm-group',
  groupTitle: 'dcm-group-title',
  option: 'dcm-option',
  optionIcon: 'dcm-option-icon',
  optionMain: 'dcm-option-main',
  optionTitle: 'dcm-option-title',
  optionDetail: 'dcm-option-detail',
  optionHint: 'dcm-option-hint',
  chevron: 'dcm-chevron',
  keys: 'dcm-keys',
  kbd: 'dcm-kbd',
  status: 'dcm-status',
  empty: 'dcm-empty',
  more: 'dcm-more',
  footer: 'dcm-footer',
  toast: 'dcm-toast',
  srOnly: 'dcm-sr-only',
  mark: 'dcm-mark',
} as const
