// Regenerates src/client/marks.generated.ts from the pinned `simple-icons`
// devDependency (CC0-1.0), keeping only the title and SVG path of the provider
// marks the picker uses. Run: pnpm run marks. With --check it only reports
// (exit 1) whether the committed file differs from what it would write.
import { readFileSync, writeFileSync } from 'node:fs'
import * as icons from 'simple-icons'

export const SLUGS = [
  'alibabacloud', 'anthropic', 'baidu', 'bytedance', 'cloudflare', 'deepseek', 'githubcopilot', 'googlegemini',
  'huggingface', 'kimi', 'lmstudio', 'meta', 'minimax', 'mistralai', 'moonshotai', 'nvidia', 'ollama', 'openrouter',
  'perplexity', 'qwen', 'tencenthy', 'vercel',
]

/** @returns the generated module text. */
export function render() {
  const lines = [
    '// Generated by scripts/marks.mjs from simple-icons (CC0-1.0); do not edit.',
    '/** Provider marks by simple-icons slug: title and 24x24 SVG path. */',
    'export const MARKS = {',
  ]
  for (const slug of SLUGS) {
    const icon = icons[`si${slug[0].toUpperCase()}${slug.slice(1)}`]
    if (icon === undefined) throw new Error(`simple-icons has no "${slug}"`)
    lines.push(`  ${slug}: { title: ${JSON.stringify(icon.title)}, path: ${JSON.stringify(icon.path)} },`)
  }
  lines.push('} as const', '')
  return lines.join('\n')
}

const TARGET = new URL('../src/client/marks.generated.ts', import.meta.url)

if (process.argv.includes('--check')) {
  if (readFileSync(TARGET, 'utf8') !== render()) {
    console.error('src/client/marks.generated.ts is stale; run `pnpm run marks`')
    process.exit(1)
  }
} else {
  writeFileSync(TARGET, render())
}
